project:
  type: website

website:
  title: "CDC Mortality Trend Analyzer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: report.qmd
        text: Pipeline

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
